### ISSUE TITLE
Q: How exactly can you create the most simple token?

### ISSUE THREAD

**Issue by croqaz** [rs/eve-auth-jwt#6]
How can we create a simple token, using eve and jwt?
What fields are required?

Maybe implementing a route like /api/auth directly in the eve-auth-jwt would be a nice feature?
Thanks!

**Comment by bretkikehara** [comment]
This module isn't an authentication service, so it doesn't create a JWT. It is simply an alternative authorization solution to basic auth. In other words, it enables eve to work with already existing JWT instances when both the eve server and the authentication server hold the same shared secret.
